name: 'C++ CI'

# Запускаем workflow при пуше в ветки lab3 или feature/github_actions
on:
  push:
    branches:
      - lab3
      - feature/github_actions

jobs:
  build_ubuntu:
    runs-on: ubuntu-latest # Запускаем на Ubuntu
    permissions: write-all # Предоставляем права на запись всем ресурсам
    steps:
      # Клонируем репозиторий, включая submodules
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      # Конфигурируем проект с помощью CMake, используя номер запуска для PATCH_VERSION
      - name: Configure with CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      # Собираем проект
      - name: Build project
        run: cmake --build .
      
      # Создаем пакет
      - name: Create package
        run: cmake --build . --target package

      # Создаем релиз для Ubuntu
      - name: Create Release (Ubuntu)
        id: create_release_ubuntu
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (Ubuntu)
          draft: false
          prerelease: false

      # Загружаем релизный ассет для Ubuntu
      - name: Upload Release Asset (Ubuntu)
        id: upload-release-asset-ubuntu
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_ubuntu.outputs.upload_url }}
          asset_path: ./laba3-0.0.${{ github.run_number }}-Linux.deb
          asset_name: laba3-0.0.${{ github.run_number }}-Linux.deb
          asset_content_type: application/vnd.debian.binary-package
          allowUpdates: true # Разрешаем обновление уже загруженного ассета

  build_macos:
    runs-on: macos-latest # Запускаем на macOS
    permissions: write-all # Предоставляем права на запись всем ресурсам
    steps:
      # Клонируем репозиторий, включая submodules
      - uses: actions/checkout@v3
        with:
          submodules: true
      
      # Конфигурируем проект с помощью CMake, используя номер запуска для PATCH_VERSION
      - name: Configure with CMake
        run: cmake . -DPATCH_VERSION=${{ github.run_number }}
      
      # Собираем проект
      - name: Build project
        run: cmake --build .
      
      # Создаем пакет
      - name: Create package
        run: cmake --build . --target package

      # Создаем релиз для macOS
      - name: Create Release (macOS)
        id: create_release_macos
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release ${{ github.run_number }} (macOS)
          draft: false
          prerelease: false

      # Загружаем релизный ассет для macOS
      - name: Upload Release Asset (macOS)
        id: upload-release-asset-macos
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release_macos.outputs.upload_url }}
          asset_path: ./laba3-0.0.${{ github.run_number }}-macos.dmg
          asset_name: laba3-0.0.${{ github.run_number }}-macos.dmg
          asset_content_type: application/x-apple-diskimage
          allowUpdates: true # Разрешаем обновление уже загруженного ассета
